### ISSUE TITLE
demo站挂了 | dmeo Hosting is Not Working

### ISSUE THREAD

**Issue by emperinter** [NiklasTiede/Github-Trending-API#4]
- demo站挂了 | dmeo Hosting is Not Working

![图片](https://user-images.githubusercontent.com/20177836/175870671-670ad117-10f6-438e-a65c-4ce1c3e7d7c6.png)

**Comment by NiklasTiede** [comment]
yes unfortunatly, heroku converted their free plan into a paid version and I will no longer deploy the Api as for the moment! I'm sorry for that!
