### ISSUE TITLE
heroku server is down. 

### ISSUE THREAD

**Issue by ankushkushwaha** [NiklasTiede/Github-Trending-API#8]
The URL https://gh-trending-api.herokuapp.com/ is not working. And all the requests, which are being made to this URL are failing.

**Comment by NiklasTiede** [comment]
unfortunately, Atlassian bought Heroku and removed the free plan. The only possibility is to run it yourself. I'm sorry :-/

**Comment by ankushkushwaha** [comment]
Okay, thanks for the information.
